import { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { PageHeader } from '../components/PageHeader';
import { ConfidenceBadge } from '../components/ConfidenceBadge';
import { CopyButton } from '../components/CopyButton';
import { EmptyState, EmptyStateIcon, EmptyStateTitle, EmptyStateDesc } from '../components/EmptyState';
import { exportToJSON, exportToCSV, exportToMarkdown, exportToPlainText, generateOnePageBrief } from '../services/exportUtilities';

export default function CRMExportPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { getCompany } = useApp();
  const company = getCompany(id || '');
  const [exportedFormat, setExportedFormat] = useState<string | null>(null);

  if (!company) {
    return (
      <div>
        <PageHeader title="CRM Export" />
        <EmptyState><EmptyStateIcon icon="🔍" /><EmptyStateTitle>Company not found</EmptyStateTitle></EmptyState>
      </div>
    );
  }

  const handleExport = (format: string) => {
    setExportedFormat(format);
    setTimeout(() => setExportedFormat(null), 3000);
  };

  const crm = company.crmExport;

  // Recon data for export
  const detectedTools = (company as any).detectedTools || [];
  const inferredWorkflows = (company as any).inferredWorkflows || [];
  const openings = (company as any).reconOpenings || [];

  // Generate recon-enhanced brief
  const generateReconBrief = () => {
    const lines: string[] = [];
    lines.push('='.repeat(60));
    lines.push(`${company.basic.name} — CRM-Ready Recon Brief`);
    lines.push('='.repeat(60));
    lines.push('');

    lines.push('DETECTED TOOLS');
    if (detectedTools.length > 0) {
      detectedTools.forEach((t: any) => lines.push(`  [${t.confidence}] ${t.toolName} (${t.category}) — ${t.evidence}`));
    } else {
      lines.push('  No tools detected from public scan');
    }
    lines.push('');

    lines.push('INFERRED WORKFLOWS');
    if (inferredWorkflows.length > 0) {
      inferredWorkflows.forEach((w: any) => lines.push(`  [${w.confidence}] ${w.workflowName} — ${w.discoveryQuestion}`));
    } else {
      lines.push('  No workflows inferred');
    }
    lines.push('');

    lines.push('AUTO-DISCOVERED OPENINGS');
    if (openings.length > 0) {
      openings.slice(0, 3).forEach((o: any) => {
        lines.push(`  Opening: ${o.title}`);
        lines.push(`  First Line: ${o.firstLine}`);
        lines.push(`  Discovery: ${o.discoveryQuestion}`);
        lines.push('  ---');
      });
    } else {
      lines.push('  No auto-discovered openings');
    }
    lines.push('');

    lines.push('RECON-BASED FIRST LINE');
    if (openings.length > 0) {
      lines.push(`  ${openings[0].firstLine}`);
    } else {
      lines.push('  N/A');
    }
    lines.push('');

    lines.push('RECON-BASED DISCOVERY QUESTIONS');
    if (openings.length > 0) {
      openings.slice(0, 3).forEach((o: any) => lines.push(`  • ${o.discoveryQuestion}`));
    } else {
      lines.push('  N/A');
    }
    lines.push('');

    lines.push('SUGGESTED DEMO PROMPT');
    if (openings.length > 0) {
      lines.push(`  ${openings[0].suggestedBuildPrompt || 'Build custom automation solution'}`);
    } else {
      lines.push('  N/A');
    }
    lines.push('');
    lines.push('-'.repeat(60));
    lines.push(`Generated by Natively Profit Scout — ${new Date().toISOString().split('T')[0]}`);
    return lines.join('\n');
  };

  if (!crm) {
    return (
      <div>
        <PageHeader title="CRM Export" subtitle={company.basic.name} />
        <EmptyState>
          <EmptyStateIcon icon="📤" />
          <EmptyStateTitle>No export data</EmptyStateTitle>
          <EmptyStateDesc>Regenerate the analysis to create CRM export data.</EmptyStateDesc>
        </EmptyState>
      </div>
    );
  }

  return (
    <div>
      <PageHeader
        title="CRM Export"
        subtitle={`${company.basic.name} — Export ready ${crm.dealStage} ${crm.prospectStatus}`}
        actions={<button className="btn btn-secondary" onClick={() => navigate(`/company/${company.id}`)}>← Company Profile</button>}
      />

      <div className="card mb-6">
        <div className="card-body">
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            <button className="btn btn-primary" onClick={() => { navigator.clipboard.writeText(exportToJSON(company)); handleExport('JSON'); }}>
              📋 Copy JSON
            </button>
            <button className="btn btn-primary" onClick={() => { navigator.clipboard.writeText(exportToCSV(company)); handleExport('CSV'); }}>
              📊 Copy CSV
            </button>
            <button className="btn btn-primary" onClick={() => { navigator.clipboard.writeText(exportToMarkdown(company)); handleExport('Markdown'); }}>
              📝 Copy Markdown
            </button>
            <button className="btn btn-primary" onClick={() => { navigator.clipboard.writeText(exportToPlainText(company)); handleExport('Text'); }}>
              📄 Copy Plain Text
            </button>
            <button className="btn btn-secondary" onClick={() => { navigator.clipboard.writeText(generateOnePageBrief(company)); handleExport('Brief'); }}>
              📋 One-Page Brief
            </button>
            <button className="btn btn-secondary" onClick={() => { navigator.clipboard.writeText(generateReconBrief()); handleExport('Recon Brief'); }}>
              📡 Recon Brief
            </button>
          </div>
          {exportedFormat && (
            <div style={{ marginTop: 12, fontSize: 13, color: '#10b981' }}>
              ✅ {exportedFormat} copied to clipboard!
            </div>
          )}
        </div>
      </div>

      <div className="card mb-6">
        <div className="card-header">
          <span className="input-label" style={{ margin: 0 }}>CRM Export Preview</span>
          <div style={{ display: 'flex', gap: 6 }}>
            <ConfidenceBadge level={crm.confidence} size="sm" />
            <span className={`badge badge-${crm.prospectStatus === 'hot' ? 'red' : crm.prospectStatus === 'warm' ? 'amber' : 'assumed'}`} style={{ fontSize: 9 }}>
              {crm.prospectStatus}
            </span>
            <span className={`badge ${crm.dealStage === 'discovery' ? 'badge-blue' : crm.dealStage === 'proposal' ? 'badge-amber' : crm.dealStage === 'closed_won' ? 'badge-green' : 'badge-assumed'}`} style={{ fontSize: 9 }}>
              {crm.dealStage}
            </span>
          </div>
        </div>
        <div className="card-body">
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, fontSize: 13 }}>
            <Field label="Company" value={crm.companyName} />
            <Field label="Website" value={crm.website} />
            <Field label="Industry" value={crm.industry} />
            <Field label="Location" value={crm.location} />
            <Field label="Employees" value={crm.companySize.toString()} />
            <Field label="Opportunity Score" value={`${crm.opportunityScore}/100`} />
            <Field label="Primary Contact" value={crm.primaryContact || 'Unknown'} />
            <Field label="Decision Maker" value={crm.decisionMaker || 'Unknown'} />
            <Field label="Champion" value={crm.champion || 'Unknown'} />
            <Field label="Recommended Product" value={crm.recommendedProduct} />
            <Field label="Package" value={crm.suggestedPackage} />
            <Field label="Next Step" value={crm.nextStep} />
            <Field label="Follow-up Date" value={crm.followupDate} />
            <Field label="Source" value={crm.source} />
          </div>

          <div style={{ marginTop: 12 }}>
            <span className="input-label" style={{ marginBottom: 8 }}>CRM Tags</span>
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
              {crm.crmTags.map((tag, i) => (
                <span key={i} className="chip chip-blue" style={{ cursor: 'default' }}>{tag}</span>
              ))}
            </div>
          </div>

          <div style={{ marginTop: 12 }}>
            <span className="input-label" style={{ marginBottom: 8 }}>Pain Points</span>
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
              {crm.painPoints.map((p, i) => (
                <span key={i} className="chip chip-amber" style={{ cursor: 'default' }}>{p}</span>
              ))}
            </div>
          </div>

          {crm.notes && (
            <div style={{ marginTop: 12 }}>
              <span className="input-label">Notes</span>
              <div style={{ fontSize: 13, color: '#94a3b8', marginTop: 4 }}>{crm.notes}</div>
            </div>
          )}

          {/* Recon Data Section */}
          {(detectedTools.length > 0 || inferredWorkflows.length > 0 || openings.length > 0) && (
            <div style={{ marginTop: 16, borderTop: '1px solid #2a3a5c', paddingTop: 16 }}>
              <span className="input-label" style={{ marginBottom: 8 }}>📡 Recon Intelligence</span>
              {detectedTools.length > 0 && (
                <div style={{ marginBottom: 8 }}>
                  <div style={{ fontSize: 11, color: '#64748b', marginBottom: 4 }}>Detected Tools:</div>
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                    {detectedTools.slice(0, 5).map((t: any, i: number) => (
                      <span key={i} className="chip chip-green" style={{ cursor: 'default', fontSize: 10 }}>
                        {t.toolName} [{t.confidence}]
                      </span>
                    ))}
                  </div>
                </div>
              )}
              {inferredWorkflows.length > 0 && (
                <div style={{ marginBottom: 8 }}>
                  <div style={{ fontSize: 11, color: '#64748b', marginBottom: 4 }}>Inferred Workflows:</div>
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                    {inferredWorkflows.slice(0, 5).map((w: any, i: number) => (
                      <span key={i} className="chip chip-amber" style={{ cursor: 'default', fontSize: 10 }}>
                        {w.workflowName} [{w.confidence}]
                      </span>
                    ))}
                  </div>
                </div>
              )}
              {openings.length > 0 && (
                <div>
                  <div style={{ fontSize: 11, color: '#64748b', marginBottom: 4 }}>Auto-Discovered Openings:</div>
                  <div style={{ fontSize: 12, color: '#94a3b8' }}>
                    First Line: {openings[0].firstLine}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      <div className="card">
        <div className="card-header">
          <span className="input-label" style={{ margin: 0 }}>One-Page Brief Preview</span>
          <CopyButton text={generateOnePageBrief(company)} label="Copy brief" />
        </div>
        <div className="card-body">
          <pre style={{ fontSize: 12, color: '#94a3b8', fontFamily: 'SF Mono, Fira Code, mono', lineHeight: 1.6, whiteSpace: 'pre-wrap', margin: 0 }}>
            {generateOnePageBrief(company)}
          </pre>
        </div>
      </div>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <span className="text-muted" style={{ fontSize: 11 }}>{label}:</span>{' '}
      <span style={{ fontSize: 13, color: '#94a3b8' }}>{value}</span>
    </div>
  );
}
